"""empty message

Revision ID: f34639f281cb
Revises: f94290bfe638
Create Date: 2020-03-29 21:13:37.452066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f34639f281cb'
down_revision = 'f94290bfe638'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("User") as batch_op:
        batch_op.add_column('User', sa.Column('FirstName', sa.String(length=100), nullable=True))
        batch_op.add_column('User', sa.Column('LastName', sa.String(length=100), nullable=True))
        batch_op.add_column('User', sa.Column('UserName', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint('UNQ_Email', 'User', ['Email'])
        batch_op.create_unique_constraint('UNQ_UserName', 'User', ['UserName'])
        batch_op.drop_column('User', 'Name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("User") as batch_op:
        batch_op.add_column('User', sa.Column('Name', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint('UNQ_UserName', 'User', type_='unique')
        batch_op.drop_constraint('UNQ_Email', 'User', type_='unique')
        batch_op.drop_column('User', 'UserName')
        batch_op.drop_column('User', 'LastName')
        batch_op.drop_column('User', 'FirstName')
    # ### end Alembic commands ###
